@startuml

CscChatRoutingStrategy <|.. CscAbstractChatRoutingStrategy
CscAbstractChatRoutingStrategy <|-- CscChatAverageRouting
CscAbstractChatRoutingStrategy <|-- CscChatLoadRouting
CscAbstractChatRoutingStrategy <|-- CscChatHistoryPriorityRouting
CscAbstractChatRoutingStrategy <|-- CscChatLimitRateRouting

interface CscChatRoutingStrategy {
    +boolean support()
    +preDistribute()
    +distribute()
    +postDistribute()
}

abstract class CscAbstractChatRoutingStrategy {
    +preDistribute()
    +distribute()
    +postDistribute()
    #doDistribute()
}

class CscChatAverageRouting {
    +boolean support()
    #doDistribute()
}

class CscChatLoadRouting {
    +boolean support()
    #doDistribute()
}

class CscChatHistoryPriorityRouting {
    +boolean support()
    #doDistribute()
}

class CscChatLimitRateRouting {
    +boolean support()
    #doDistribute()
}

@enduml